"""Detection signal functions for Provenance Guard.

Signal 1 (Milestone 3): LLM-based classification via Groq Llama 3.3.
Signal 2 (stylometric heuristics) is added in Milestone 4.
"""

import json
import os

from groq import Groq

# Score interpretation: 0.0 = clearly human, 1.0 = clearly AI.
_LLM_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are an AI-content detector. You assess whether a piece of text was "
    "written by a human or generated by an AI language model. Judge holistically: "
    "consider pacing, voice, idiosyncrasy, opinion, and stylistic coherence. "
    "AI text tends to be smoothly fluent, evenly paced, and neutral in opinion; "
    "human text has voice and quirks.\n\n"
    "Respond with ONLY a JSON object in this exact format, nothing else:\n"
    '{"score": 0.X, "reasoning": "one sentence"}\n\n'
    "where score is a float between 0.0 (clearly human) and 1.0 (clearly AI), "
    "and reasoning is a single sentence explaining your judgment."
)


def llm_signal(text: str) -> dict:
    """Assess whether `text` is human- or AI-generated using Groq Llama 3.3.

    Returns {"score": float (0.0-1.0), "reasoning": str}.
    On any parse failure, returns a neutral fallback of score 0.5.
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    completion = client.chat.completions.create(
        model=_LLM_MODEL,
        temperature=0.2,  # low — we want consistent scoring, not creativity
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )

    raw = completion.choices[0].message.content.strip()

    try:
        parsed = json.loads(_extract_json(raw))
        score = float(parsed["score"])
        # Clamp into the valid range in case the model drifts.
        score = max(0.0, min(1.0, score))
        reasoning = str(parsed["reasoning"])
        return {"score": score, "reasoning": reasoning}
    except (ValueError, KeyError, TypeError):
        return {"score": 0.5, "reasoning": "Could not parse model response"}


def _extract_json(raw: str) -> str:
    """Pull the first {...} block out of a model response.

    The model occasionally wraps JSON in prose or markdown fences; slicing from
    the first '{' to the last '}' recovers the object in those cases.
    """
    start = raw.find("{")
    end = raw.rfind("}")
    if start != -1 and end != -1 and end > start:
        return raw[start : end + 1]
    return raw
